config/routes.rb
QuickShark::Application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  resources :users do
    resources :journeys, shallow: true
  end

  resources :topics
  
  get "/login", to: "session#new"
  post "/session", to: "session#create"
  delete "/session", to: "session#destroy"

  root "topics#new"

  get "/data", to: "topics#data"
  get "/definitions", to: "topics#definition"
  get "/description", to: "topics#description"
  get "/pictures", to: "topics#pictures"
  get "/stats", to: "topics#stats"

  post "/add_topic", to: "topics#add_topic"

  get "/ytdata", to: "topics#ytdata"


  # # PJ: Below is a suggeseted direction for your routes, to make them fit a more 
  # # RESTful convention. For more, see: http://guides.rubyonrails.org/routing.html
  
  # # your groups interface is very simple, and you got it mostly right...
  # root "topics#new"

  # resource  :session, only: [:new, :create, :destroy] # singular resource, maybe not with new

  # resources :users, shallow: true do
  #   resources :journeys do
  #     resources :tangents, only: [:create, :show]
  #   end
  # end

  # # this can be for future features, actually unnecessary now...
  # # resources :topics, only: [:index, :show]

  # # above, when you're getting data, definition, description, pictures, stats, and ytdata
  # # you should just be loading that from the tangent#show onto the page in the first place,
  # # if that content is then loaded by the browser asynchronously
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :tangents
  has_many :journeys, through: :tangents
  validates :name, presence: true, uniqueness: true
  
  def to_param
    name
  end
  
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  include TopicsHelper

  def new
    @random_word = get_random_word["word"]
  end

  def create
    unless params[:topic]["topic"].empty?
      @topic = Topic.find_by(name: params["topic"]["topic"]) || Topic.create(name: params["topic"]["topic"])

      if current_user
        @journey = Journey.create(title: params["topic"]["topic"], user_id: current_user[:id])
        @journey.topics << @topic
      end

      redirect_to topic_path( @topic, journey_id: @journey.try(:id) )

    else
      redirect_to root_path
    end
  end

  def show
    @topic = Topic.find_by(name: params[:id])

    if current_user && params[:journey_id]
      @journey = Journey.find_by(id: params[:journey_id])
    end

    @word_association = get_word_associations(@topic.name)
    @videos = get_youtube_vids(@topic.name).take(4)
  end

  def description
    @description = find_topic_description(params[:name])
    render json: @description
  end

  def definition
    @definition = get_word_associations(params[:name])
    render json: @definition
  end

  def pictures
    # Find the photo by the topic you are searching
    @photo = find_photo(params[:name])
    # Render JSON object to /pictures route for access later
    render json: @photo
  end

  def stats
    @wolfram = get_wolfram_alpha(params[:name])
    render json: @wolfram
  end

  def data
    if Topic.find_by(name: params[:word] ) !=  nil
      @topic = Topic.find_by(name: params[:word] )
      else
      @topic = Topic.create(name: params[:word])
    end
    @word_association = get_word_associations(@topic[:name])
    if @word_association[0][:word_associations].nil?
      @tree = tree_results(get_wolfram_text(@topic.name))
      render json: @tree_data
    else
      @tree = tree_results(@word_association[0])
      if @tree["children"][2]["children"] != nil
        render json: @tree.to_json
      else
        render json: {"name" => "No Results"}
      end
    end
  end

  def add_topic
    @topic =  Topic.find_by(name: params[:topic]) || Topic.create(name: params[:topic])

    if current_user
      @journey = Journey.find(params[:journey])
      @journey.topics << @topic
      render json: @topic
    end
  end

  def ytdata
    # Set topic name
    @topic = Topic.find_by(name: params[:name] )
    # Find Youtube JSON object by topic name
    @video_data = youtube_json(@topic.name)
    # Render JSON object to /ytdata route for access later
    render json: @video_data
  end

  def update
    @topic = Topic.find(params[:id])
    @topic.save
    render json: @topic
  end

  private

  def get_random_word
    randomWord = HTTParty.get("http://api.wordnik.com:80/v4/words.json/randomWord?hasDictionaryDef=true&minCorpusCount=0&maxCorpusCount=-1&minDictionaryCount=10&maxDictionaryCount=-1&minLength=5&maxLength=-1&api_key="+WORDNIK_API_KEY)
  end

end

app/helpers/topics_helper.rb
module TopicsHelper

  def get_wolfram_alpha(word)
    # Initial API call, results passed into an array of a hash
    wolfram = []
    stuff = HTTParty.get('http://api.wolframalpha.com/v2/query?input='+word.gsub(" ", "%20").downcase+'&appid='+WOLFRAM_ALPHA_API_KEY)
    stuff["queryresult"]["pod"].each do |subpod|
      unless subpod["subpod"].class == Array
        wolfram.push(Hash["plaintext", subpod["subpod"]["plaintext"], "image", subpod["subpod"]["img"]])
      end
    end
    wolfram
  end

  def get_word_associations(word)
    # Initial API call, results passed into an array of a hash
    word_association = [{
      word: word,
      # HTTP get returns JSON objects then pushed into arrays
      definitions: HTTParty.get('http://api.wordnik.com:80/v4/word.json/'+word.gsub(" ", "%20").downcase+'/definitions?limit=200&includeRelated=true&useCanonical=true&includeTags=false&api_key='+WORDNIK_API_KEY).map,
      word_associations: HTTParty.get('http://api.wordnik.com:80/v4/word.json/'+word.gsub(" ", "%20").downcase+'/relatedWords?limit=2&useCanonical=true&limitPerRelationshipType=10&api_key='+WORDNIK_API_KEY).map,
      reverse_definitions: HTTParty.get('http://api.wordnik.com:80/v4/words.json/reverseDictionary?query='+word.gsub(" ", "%20").downcase+'&minCorpusCount=5&maxCorpusCount=-1&minLength=1&maxLength=-1&includeTags=false&skip=0&limit=5&api_key='+WORDNIK_API_KEY)
      }]
    # Setting definitions as word parameters for word tree
    word_association[0][:definitions].each do |definition|
      definition["word"] = "definition"
    end
  word_association
  end

  def find_topic_description(description)
    # Initial API call
    url = Addressable::URI.parse('https://www.googleapis.com/freebase/v1/search')

    # Set the parameters of the API call
    url.query_values = {
      query: description,
      type: "/common/topic"
    }

    # Call again to return a JSON object for the selected query
    from_freebase = HTTParty.get(url, :format => :json)
    # fallback logic
    if from_freebase["result"].length == 0
      return "No description available"
    else
      # Parsing out the description of the query
      wordTree = []
      mid = from_freebase["result"][0]["mid"]
      description = HTTParty.get("https://www.googleapis.com/freebase/v1/topic#{mid}?filter=/common/topic/description", :format => :json)
      description = description["property"]["/common/topic/description"]["values"][0]["value"]
    end
  end

  def find_photo(tags)
    # Inital Flickr API call, "tags" is the search query
    result = flickr.photos.search(
      :tags => tags,
      # Parameter that returns Gettyimages.com quality pictues
      :is_getty => true
      )
    # If there are no pictues, you get an "error" image
    if result.length == 0
      url = []
      4.times do
        url = url.push("http://www.yiyinglu.com/failwhale/images/Homer_the_New_Fail_Whale_by_edwheeler.jpg")
      end
    else
      # pick 4 random photo id's
      photo_array = []
      4.times do
        photo_array = photo_array.push(result[rand(result.length)]["id"])
      end
      # plug 4 random id's in to get info back
      info_array = photo_array.map do |id|
       flickr.photos.getInfo(:photo_id => id)
      end
      # plug info into FlickRaw to extract url
      url = info_array.map do |info|
        FlickRaw.url(info)
      end
    end
    return url
  end

# formatting the incoming results from wordnik to the proper nested format
  def tree_results(word_data)
    #get the data ready for d3 view
    tree_data = {"name"=> (@topic.name), "info" => "tst", "children" => []}
    
    word_data.each do |text, v|
      tree_data["children"].push({"name" => text.to_s, "children" => []})
    end
    
    tree_data["children"][0]["children"] << Hash["name", word_data[:word]]
    
    word_data[:definitions].each do |text|
      tree_data["children"][1]["children"] << Hash["name", text["text"]]
    end
    
    word_data[:word_associations].each do |text|
      tree_data["children"][2]["children"] << Hash["name", text["relationshipType"], "children", []]
    end     
    if word_data[:reverse_definitions]["results"].nil? 
      tree_data["children"][3]["children"] << nil
    else
      word_data[:reverse_definitions]["results"].each do |result| 
        tree_data["children"][3]["children"] << Hash["name", result["text"]]
      end
    end
    i = 0
    word_data[:word_associations].each do |text|
      text["words"].each do |word|
        tree_data["children"][2]["children"][i]["children"] << Hash["name", word]
      end
      i+=1
    end
    #reduce duplicates in word_association hash
    tree_data["children"][3]["children"].uniq!
    tree_data["children"][2]["children"].uniq!
    return tree_data
  end

  def get_youtube_vids(query)
    video_results = []
    # Get results from Youtube API in JSON format
    full_results = HTTParty.get(
      "https://www.googleapis.com/youtube/v3/search?part=snippet&q=#{query.gsub(" ", "%20")}&maxResults=10&key="+YOUTUBE_API_KEY
      )
    # Push the video ID and title of each vide in an array of arrays
    full_results["items"].each do |result|
      video_results.push([result["id"]["videoId"], result["snippet"]["title"]])
    end
    return video_results
  end

  # Same method as above, except leaving the JSON object as is
  # Used to create an API to access the data later
  def youtube_json(query)
    full_results = HTTParty.get("https://www.googleapis.com/youtube/v3/search?part=snippet&q=#{query.gsub(" ", "%20")}&maxResults=50&key="+YOUTUBE_API_KEY)
    return full_results
  end
end

app/views/topics/new.html.erb
<div class="container">
  
  <%= form_for :topic, url: topics_path, :html => {:id => "explore" } do |f| %>
    <%= f.search_field :topic, placeholder: "Enter Any Word, Topic, Idea, etc.", autofocus: "autofocus", autocomplete: "off" %><br />
    <p class="perspective">
        <button class="btn intro-button number1" id="exploreB" disabled="true">
          <svg class="icon">
            <use xlink:href="#compass"></use>
          </svg>
          Explore
        </button>
      </p>
  <% end %>
    
  <%= form_for :topic, url: topics_path, :html => {:id => "random"} do |f| %>
    <%= f.hidden_field :topic, :value => @random_word %>
    <p class="perspective">
        <button id="randomB"class="btn intro-button number2" onKeyPress=”return disableEnterKey(event)”>
          <svg class="icon">
            <use xlink:href="#shuffle"></use>
          </svg>
          Random
        </button>
      </p>
    
  <% end %>
   
</div>

<script type="text/javascript">
function disableEnterKey(e)
{
     var key;      
     if(window.event)
          key = window.event.keyCode; //IE
     else
          key = e.which; //firefox      

     return (key != 13);
}

</script>

<script type="text/javascript">
/*deactivates explore button if search input is empty */
  $( "input#topic_topic" ).on("keyup", function(e) { 
    if(67 < e.keyCode && e.keyCode < 90) {
      $( "button#exploreB" ).prop('disabled', false);
    }
  });
</script>


<script type="text/javascript">
// hover for instructions
  var wordList = ["atlas", "apple", "journey", "discovery", "ball", "angel", "query", "trite", "spiteful", "anarchy", "decay", "stupor", "stupdendous", "brain", "petite", "luxury", "game", "peanut", "egg", "forlorn", "milky way", "shark", "fish", "paris", "america", "chocolate", "ocean", "cat", "dog", "human", "heart", "love", "passion", "fury", "death", "anger", "annoyed", "friend", "enemy", "nostalgia", "pity", "pitiful", "dogma", "heresy", "prison", "compassion", "energy", "bacon", "poop", "eureka"];
  function words(){
    word1 = wordList[Math.floor(Math.random()*wordList.length)];
    word2 = wordList[Math.floor(Math.random()*wordList.length)]
    if(word1 === word2){
      word2 =  wordList[Math.floor(Math.random()*wordList.length)]
    }
    return [word1, word2]
  };
  
  $("body").attr("title","Input any search term here to see a tree of relationships. Try  <em>'"+ words()[0] +"'</em>   or   '<em>"+ words()[1] +"'</em> , or click  <em>'Random'</em>    to let us choose for you.");
  $("body").tooltipsy({alignTo: $("input#topic_topic"), offset: [0, -30], delay: 2000, className: 'searchbar_tooltipsy'});
</script>

app/views/topics/show.html.erb
<% if @journey %>
  <div style="display:none;" id='journey'> Current Journey: <span><%= @journey[:title] %></span> </div><span id="journey_id" style="display: none;"><%= @journey[:id] %></span>
  <div id='past_topics'><a id='sup' data-tooltip='<%= @topic.name %>'><div class='bubble'></div></a>
</div>
<% end %>

  <div><h1 style="display:none;"><%= @word_association[0][:word] %></h1><% unless !@word_association[0][:reverse_definitions].nil? %><span><%=@word_association[0][:reverse_definitions]["results"].sample["text"] %> <% end %>
  </div>

<% if @journey %>
  <%= button_to "End Journey" , journey_path(@journey.id) , method: "get", id: "end_journey" %>
<% end %>

<div id="define"><h2>Random Description</h2><p id="description"> <%= @description %> </p>
  <div id="definitions"><h2>Definitions<h2><p><p></div>
  <div id="reverse_definitions"><h2>Reverse Definitions<h2><p><p></div>
  </div>
</div>

<div id="pictures"><h2>Related Pictures</h2></div>
<div id="videos"><h2>Related Videos</h2></div>
<div id="stats"><h2>Related Info</h2></div>

</div>


<span id="topic_id" style="display:none"><%=@topic.id%></span>
<%= javascript_include_tag "treediagram" %>
<div id="viz"></div>
<div class="arrow-right">
  <svg viewBox="0 0 50 50" class="pannel-icons" id="icon-right">
    <use xlink:href="#dashboard-speed"></use>
  </svg>
</div>
<div class="arrow-left">
  <svg viewBox="0 0 50 50" class="pannel-icons" id="icon-left">
    <use xlink:href="#camera-video"></use>
  </svg>
</div>
<div class="arrow-top">
  <svg viewBox="0 0 50 50" class="pannel-icons" id="icon-top">
    <use xlink:href="#receipt-shopping"></use>
  </svg>
</div>
<div class="arrow-bottom">
  <svg viewBox="0 0 50 50" class="pannel-icons" id="icon-bottom">
    <use xlink:href="#picture-stock"></use>
  </svg>
</div>

 <div class="nav-key-container">
      <div class="nav-commands">
        <div class="arrow-row">
          <div class="fake-key"></div>
          <div class="arrow-key" id="up-arrow">↑</div>
          <div class="fake-key"></div>
        </div>
        <div class="arrow-row">
          <div class="arrow-key" id="left-arrow">←</div>
          <div class="arrow-key" id="down-arrow">↓</div>
          <div class="arrow-key" id="right-arrow">→</div>
        </div>
        <div class="clear-row">
          <div id="clear-key">c</div>
        </div>
      </div>
      <div class="keys">
          <ul class="key-container">
            <li><span class="key">key up:</span> pictures</li>
            <li><span class="key">key down:</span> description</li>
            <li><span class="key">key left:</span> stats</li>
            <li><span class="key">key right:</span> videos</li>
            <li><span class="key">c:</span> clear the screen</li>
          </ul>
        </div>
      </div>

<script>
  $(document).ready( function(){
    makeTimeline();
  });
</script>
<script>
  $("body").append("<div id='side-instructions'><p>Click on a word...Push the arrow keys...Click and drag...Scroll to zoom.</p></div>");
  $(window).mousemove(function() {
    setTimeout( function() {
      $('#side-instructions').css("display", "hidden");
    }, 5000);
  })
</script>