config/routes.rb
QuickShark::Application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  resources :users do
    resources :journeys, shallow: true
  end

  resources :topics
  
  get "/login", to: "session#new"
  post "/session", to: "session#create"
  delete "/session", to: "session#destroy"

  root "topics#new"

  get "/data", to: "topics#data"
  get "/definitions", to: "topics#definition"
  get "/description", to: "topics#description"
  get "/pictures", to: "topics#pictures"
  get "/stats", to: "topics#stats"

  post "/add_topic", to: "topics#add_topic"

  get "/ytdata", to: "topics#ytdata"


  # # PJ: Below is a suggeseted direction for your routes, to make them fit a more 
  # # RESTful convention. For more, see: http://guides.rubyonrails.org/routing.html
  
  # # your groups interface is very simple, and you got it mostly right...
  # root "topics#new"

  # resource  :session, only: [:new, :create, :destroy] # singular resource, maybe not with new

  # resources :users, shallow: true do
  #   resources :journeys do
  #     resources :tangents, only: [:create, :show]
  #   end
  # end

  # # this can be for future features, actually unnecessary now...
  # # resources :topics, only: [:index, :show]

  # # above, when you're getting data, definition, description, pictures, stats, and ytdata
  # # you should just be loading that from the tangent#show onto the page in the first place,
  # # if that content is then loaded by the browser asynchronously
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :journeys
  validates :email, presence: :true, uniqueness: :true 
  has_secure_password
  validates :password_digest, presence: :true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :load_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, :authorize, only: [:show, :edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render(:new)
    end
  end

  def show
  end

  def edit
    @update_worked = true
  end

  def destroy
    @user.destroy
    session.destroy
    redirect_to root_path
  end

  def update
    @update_worked = @user.update(user_params)
    if @update_worked
      redirect_to user_path(@user)
    else
      render(:edit)
    end
  end
  
  private

  def load_user
    return @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def authenticate
    unless logged_in?
      redirect_to root_path
    end
  end

  def authorize
    unless current_user == @user
      redirect_to root_path
    end
  end
end

app/views/users/_form.html.erb
<div class="new-user-form">
  <%= form_for @user do |f| %>

  <%= f.label :first_name %><br/>
  <%= f.text_field :first_name %>
  <br/>

  <%= f.label :last_name %><br/>
  <%= f.text_field :last_name %>
  <br/>

  <%= f.label :email %><br/>
  <%= f.email_field :email %>
  <br/>

  <%= f.label :password %><br/>
  <%= f.password_field :password %>
  <br/>

  <%= f.label :password_confirmation %><br/>
  <%= f.password_field :password_confirmation %>
  <br/>
  <br/>
  <%= f.submit @user.id.nil? ? "Join" : "Save Changes" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<% unless @update_worked %>
<div id="errors">
  <h3>Errors!</h3>
  <ul>
    <% @user.errors.messages.each do |field,error| %>
    <li><em><%= "#{field.capitalize} #{error.first}!" %></em></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= render "form" %>

app/views/users/new.html.erb
<% unless @user.nil? || @user.id.nil? %>
  <div id="errors">
    <h3>Errors!</h3>
    <ul>
      <% @user.errors.messages.each do |field,error| %>
        <li><em><%= "#{field.capitalize} #{error.first}!" %></em></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= render "form" %>

app/views/users/show.html.erb
<div class="journey_wrapper">
  <h2 class="saved_headline"><%= @user.first_name %>'s Saved Journeys</h2>
  <%= link_to "Edit My Info", edit_user_path(@user), class: "edit-account" %>

<%= form_tag user_path(@user), method: "delete", class: "delete-account" do %>
<%= submit_tag("Delete My Account") %>
<% end %>
  <span class="journey_title">
  <ul id="user_journey_list" class="journey-item">
    <% journey_list = Journey.where(user_id: @user.id) %>
    <% journey_list.each do |journey| %>
      <li><%= link_to journey.title, journey_path(journey.id), method: "get", class: "view-journey"  %>
      <%= button_to "Delete" , journey_path(journey.id) , method: "delete" %></li>
    <% end %>
  </ul>
  </span> 
</div>